# Generated by Django 2.2 on 2022-05-19 05:32

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('movie_duration', models.IntegerField(default=60, verbose_name='Movie Duration')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='Image')),
                ('trailer_link', models.URLField(verbose_name='Trailer Link')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('ratings', models.IntegerField(verbose_name='Rating')),
                ('release_type', models.CharField(choices=[('Newly Released', 'Newly Released'), ('Upcoming Movies', 'Upcoming Movies')], max_length=50, verbose_name='Released Type')),
                ('released_date', models.IntegerField(verbose_name='Released Date')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='categories.Category')),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
